apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service.yaml
- preview-service.yaml
images:
- name: maverick96k/vote-ui
  newName: maverick96k/vote-ui
  newTag: stable-v3
